import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sanket Shivam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{backgroundColor: '#f9f9f9'}}>{children}</body>
    </html>
  );
}
